/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const get_version: () => [number, number];
export const verify_location: () => number;
export const get_cookie: (a: number, b: number) => [number, number];
export const set_cookie: (a: number, b: number, c: number, d: number, e: number) => void;
export const delete_cookie: (a: number, b: number) => void;
export const refresh_cookies: () => void;
export const check_login_status: () => number;
export const encrypt_xor: (a: number, b: number) => [number, number];
export const verify_answer: (a: number, b: number, c: number, d: number) => number;
export const create_answer_hash: (a: number, b: number) => [number, number];
export const generate_block_sequence: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const get_block_color: (a: number, b: number) => [number, number];
export const calculate_score: (a: number, b: number, c: number, d: number) => number;
export const create_game_token: (a: number, b: number, c: number, d: bigint) => [number, number];
export const verify_game_token: (a: number, b: number, c: number, d: bigint, e: number, f: number) => number;
export const verify_timing: (a: number, b: number) => number;
export const can_use_bomb: (a: number) => number;
export const reset_bomb_usage: () => void;
export const can_undo: () => number;
export const increment_undo: () => void;
export const reset_undo_count: () => void;
export const get_undo_count: () => number;
export const encrypt_score_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: bigint) => [number, number];
export const decrypt_score_data: (a: number, b: number) => [number, number];
export const generate_seed: () => number;
export const init: () => void;
export const hash_answer: (a: number, b: number) => [number, number];
export const decrypt_xor: (a: number, b: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
