/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_manuscriptengine_free: (a: number, b: number) => void;
export const manuscriptengine_new: (a: number, b: number) => number;
export const manuscriptengine_set_teacher_mode: (a: number, b: number) => void;
export const manuscriptengine_get_state: (a: number) => any;
export const manuscriptengine_process_char: (a: number, b: number, c: number) => any;
export const manuscriptengine_flush_waiting_char: (a: number) => any;
export const manuscriptengine_backspace: (a: number) => any;
export const manuscriptengine_move_left: (a: number) => any;
export const manuscriptengine_move_right: (a: number) => any;
export const manuscriptengine_toggle_error_mark: (a: number, b: number, c: number) => any;
export const manuscriptengine_clear_error_marks: (a: number) => any;
export const manuscriptengine_load_content: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const manuscriptengine_get_teacher_text: (a: number) => [number, number];
export const manuscriptengine_get_student_text: (a: number) => [number, number];
export const manuscriptengine_get_error_text: (a: number) => [number, number];
export const manuscriptengine_copy_student_to_teacher: (a: number) => any;
export const manuscriptengine_clear_teacher_cells: (a: number) => any;
export const authenticate_student: (a: number, b: number, c: number, d: number) => any;
export const authenticate_teacher: (a: number, b: number, c: number, d: number) => any;
export const save_manuscript: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => any;
export const load_manuscripts: (a: number, b: number, c: number, d: number) => any;
export const load_manuscript_by_id: (a: number) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure78_externref_shim: (a: number, b: number, c: any) => void;
export const closure95_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
