/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_inputhandler_free: (a: number, b: number) => void;
export const inputhandler_new: (a: number, b: number) => number;
export const inputhandler_set_position: (a: number, b: number) => void;
export const inputhandler_get_position: (a: number) => number;
export const inputhandler_start_composition: (a: number) => void;
export const inputhandler_end_composition: (a: number) => void;
export const inputhandler_is_composing: (a: number) => number;
export const inputhandler_update_composition: (a: number, b: number, c: number) => any;
export const inputhandler_finalize_composition: (a: number, b: number, c: number) => any;
export const inputhandler_process_input: (a: number, b: number, c: number) => any;
export const inputhandler_handle_space: (a: number) => any;
export const inputhandler_handle_backspace: (a: number) => any;
export const inputhandler_finalize_buffer: (a: number) => any;
export const inputhandler_move_left: (a: number) => number;
export const inputhandler_move_right: (a: number) => number;
export const inputhandler_move_up: (a: number) => number;
export const inputhandler_move_down: (a: number) => number;
export const inputhandler_move_next_row: (a: number) => number;
export const inputhandler_get_buffer_state: (a: number) => any;
export const inputhandler_handle_delete: (a: number) => any;
export const init: () => void;
export const authenticate_student: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const save_manuscript: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const load_manuscript_list: (a: number, b: number, c: number, d: number) => any;
export const load_existing_files: (a: number, b: number, c: number, d: number) => any;
export const update_manuscript: (a: number, b: number, c: number, d: number) => any;
export const check_manuscript_exists: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const wasm_bindgen__convert__closures_____invoke__hd9967afd98a984bb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__he0dfb8770d4ad62e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h86ba8cdd7f9830c4: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
